"""Database seed script for initial data."""
from uuid import uuid4
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from src.models.checklist import ChecklistTemplate
from src.models.decision import DecisionTree, DecisionNode


async def seed_checklist_templates(db: AsyncSession):
    """Seed checklist templates for all phases."""

    # Check if already seeded
    result = await db.execute(select(ChecklistTemplate).limit(1))
    if result.scalar_one_or_none():
        print("Checklist templates already seeded")
        return

    templates = [
        # ===== DETECTION PHASE =====
        {
            "item_id": "det_001",
            "phase": "detection",
            "text": "Review initial alert and event data",
            "text_de": "Erste Warnmeldung und Ereignisdaten überprüfen",
            "help_text": "Examine the triggering alert, log entries, and any automated detection data",
            "help_text_de": "Überprüfen Sie die auslösende Warnung, Protokolleinträge und automatische Erkennungsdaten",
            "mandatory": True,
            "forensic_critical": False,
            "order": 1,
        },
        {
            "item_id": "det_002",
            "phase": "detection",
            "text": "Validate the incident is not a false positive",
            "text_de": "Überprüfen, dass es sich nicht um einen Fehlalarm handelt",
            "help_text": "Cross-reference multiple data sources to confirm the alert",
            "help_text_de": "Überprüfen Sie mehrere Datenquellen, um die Warnung zu bestätigen",
            "mandatory": True,
            "forensic_critical": False,
            "order": 2,
            "depends_on": ["det_001"],
        },
        {
            "item_id": "det_003",
            "phase": "detection",
            "text": "Document initial indicators of compromise (IOCs)",
            "text_de": "Erste Kompromittierungsindikatoren (IOCs) dokumentieren",
            "help_text": "Record IP addresses, file hashes, domains, and other IOCs",
            "help_text_de": "IP-Adressen, Datei-Hashes, Domains und andere IOCs erfassen",
            "mandatory": True,
            "forensic_critical": True,
            "order": 3,
            "depends_on": ["det_002"],
        },
        {
            "item_id": "det_004",
            "phase": "detection",
            "text": "Determine initial scope and affected systems",
            "text_de": "Ersten Umfang und betroffene Systeme ermitteln",
            "help_text": "Identify potentially affected hosts, networks, and users",
            "help_text_de": "Potenziell betroffene Hosts, Netzwerke und Benutzer identifizieren",
            "mandatory": True,
            "forensic_critical": False,
            "order": 4,
            "depends_on": ["det_003"],
        },
        {
            "item_id": "det_005",
            "phase": "detection",
            "text": "Assign incident severity and priority",
            "text_de": "Schweregrad und Priorität des Vorfalls zuweisen",
            "help_text": "Based on impact and urgency, classify the incident",
            "help_text_de": "Klassifizieren Sie den Vorfall basierend auf Auswirkung und Dringlichkeit",
            "mandatory": True,
            "forensic_critical": False,
            "order": 5,
            "depends_on": ["det_004"],
        },
        {
            "item_id": "det_006",
            "phase": "detection",
            "text": "Notify incident response team",
            "text_de": "Incident-Response-Team benachrichtigen",
            "help_text": "Alert the appropriate team members based on severity",
            "help_text_de": "Benachrichtigen Sie die entsprechenden Teammitglieder basierend auf dem Schweregrad",
            "mandatory": True,
            "forensic_critical": False,
            "order": 6,
            "depends_on": ["det_005"],
        },

        # ===== ANALYSIS PHASE =====
        {
            "item_id": "ana_001",
            "phase": "analysis",
            "text": "Preserve volatile evidence",
            "text_de": "Flüchtige Beweise sichern",
            "help_text": "Capture memory, running processes, network connections before they are lost",
            "help_text_de": "Erfassen Sie Speicher, laufende Prozesse und Netzwerkverbindungen",
            "warning": "FORENSIC WARNING: Failure to preserve volatile evidence may destroy critical data",
            "warning_de": "FORENSIK-WARNUNG: Ohne Sicherung können kritische Daten verloren gehen",
            "mandatory": True,
            "forensic_critical": True,
            "order": 1,
        },
        {
            "item_id": "ana_002",
            "phase": "analysis",
            "text": "Create forensic images of affected systems",
            "text_de": "Forensische Abbilder der betroffenen Systeme erstellen",
            "help_text": "Bit-for-bit copies of storage media for investigation",
            "help_text_de": "Bit-für-Bit-Kopien der Speichermedien für die Untersuchung",
            "warning": "Use write-blockers to prevent evidence contamination",
            "warning_de": "Verwenden Sie Schreibblocker, um Beweiskontamination zu verhindern",
            "mandatory": True,
            "forensic_critical": True,
            "order": 2,
            "depends_on": ["ana_001"],
        },
        {
            "item_id": "ana_003",
            "phase": "analysis",
            "text": "Analyze malware samples",
            "text_de": "Malware-Proben analysieren",
            "help_text": "Static and dynamic analysis of suspicious files",
            "help_text_de": "Statische und dynamische Analyse verdächtiger Dateien",
            "mandatory": False,
            "forensic_critical": False,
            "order": 3,
        },
        {
            "item_id": "ana_004",
            "phase": "analysis",
            "text": "Determine attack vector and entry point",
            "text_de": "Angriffsvektor und Eintrittspunkt ermitteln",
            "help_text": "How did the attacker gain initial access?",
            "help_text_de": "Wie hat der Angreifer den Erstzugang erlangt?",
            "mandatory": True,
            "forensic_critical": False,
            "order": 4,
            "depends_on": ["ana_002"],
        },
        {
            "item_id": "ana_005",
            "phase": "analysis",
            "text": "Map lateral movement and privilege escalation",
            "text_de": "Laterale Bewegung und Rechteausweitung kartieren",
            "help_text": "Trace the attacker's path through the network",
            "help_text_de": "Verfolgen Sie den Weg des Angreifers durch das Netzwerk",
            "mandatory": True,
            "forensic_critical": False,
            "order": 5,
            "depends_on": ["ana_004"],
        },
        {
            "item_id": "ana_006",
            "phase": "analysis",
            "text": "Identify all compromised accounts",
            "text_de": "Alle kompromittierten Konten identifizieren",
            "help_text": "List user and service accounts used by the attacker",
            "help_text_de": "Benutzer- und Dienstkonten des Angreifers auflisten",
            "mandatory": True,
            "forensic_critical": False,
            "order": 6,
            "depends_on": ["ana_005"],
        },
        {
            "item_id": "ana_007",
            "phase": "analysis",
            "text": "Assess data exfiltration",
            "text_de": "Datenexfiltration bewerten",
            "help_text": "Determine if and what data was stolen",
            "help_text_de": "Ermitteln Sie, ob und welche Daten gestohlen wurden",
            "mandatory": True,
            "forensic_critical": True,
            "order": 7,
        },

        # ===== CONTAINMENT PHASE =====
        {
            "item_id": "con_001",
            "phase": "containment",
            "text": "Isolate affected systems from network",
            "text_de": "Betroffene Systeme vom Netzwerk isolieren",
            "help_text": "Prevent further spread while preserving evidence",
            "help_text_de": "Weitere Ausbreitung verhindern und Beweise sichern",
            "warning": "Do NOT power off systems - this destroys volatile evidence",
            "warning_de": "Systeme NICHT ausschalten - dies zerstört flüchtige Beweise",
            "mandatory": True,
            "forensic_critical": True,
            "order": 1,
        },
        {
            "item_id": "con_002",
            "phase": "containment",
            "text": "Block attacker's command and control channels",
            "text_de": "Command-and-Control-Kanäle des Angreifers blockieren",
            "help_text": "Firewall rules to block C2 IPs, domains",
            "help_text_de": "Firewall-Regeln zum Blockieren von C2-IPs und Domains",
            "mandatory": True,
            "forensic_critical": False,
            "order": 2,
            "depends_on": ["con_001"],
        },
        {
            "item_id": "con_003",
            "phase": "containment",
            "text": "Disable compromised user accounts",
            "text_de": "Kompromittierte Benutzerkonten deaktivieren",
            "help_text": "Reset passwords and revoke sessions",
            "help_text_de": "Passwörter zurücksetzen und Sitzungen widerrufen",
            "mandatory": True,
            "forensic_critical": False,
            "order": 3,
        },
        {
            "item_id": "con_004",
            "phase": "containment",
            "text": "Implement emergency access controls",
            "text_de": "Notfall-Zugriffskontrollen implementieren",
            "help_text": "Restrict access to critical systems during response",
            "help_text_de": "Zugriff auf kritische Systeme während der Reaktion einschränken",
            "mandatory": True,
            "forensic_critical": False,
            "order": 4,
        },
        {
            "item_id": "con_005",
            "phase": "containment",
            "text": "Monitor for attacker re-entry attempts",
            "text_de": "Auf Wiedereintrittsversuche des Angreifers überwachen",
            "help_text": "Enhanced monitoring on containment boundaries",
            "help_text_de": "Verstärkte Überwachung an Eindämmungsgrenzen",
            "mandatory": True,
            "forensic_critical": False,
            "order": 5,
            "depends_on": ["con_002"],
        },

        # ===== ERADICATION PHASE =====
        {
            "item_id": "era_001",
            "phase": "eradication",
            "text": "Remove malware and backdoors",
            "text_de": "Malware und Hintertüren entfernen",
            "help_text": "Clean infected systems or reimage from known-good backups",
            "help_text_de": "Infizierte Systeme bereinigen oder von bekannten Backups neu erstellen",
            "mandatory": True,
            "forensic_critical": False,
            "order": 1,
        },
        {
            "item_id": "era_002",
            "phase": "eradication",
            "text": "Patch exploited vulnerabilities",
            "text_de": "Ausgenutzte Schwachstellen patchen",
            "help_text": "Apply security patches that address the attack vector",
            "help_text_de": "Sicherheitspatches anwenden, die den Angriffsvektor adressieren",
            "mandatory": True,
            "forensic_critical": False,
            "order": 2,
        },
        {
            "item_id": "era_003",
            "phase": "eradication",
            "text": "Reset all potentially compromised credentials",
            "text_de": "Alle potenziell kompromittierten Anmeldedaten zurücksetzen",
            "help_text": "Including service accounts and API keys",
            "help_text_de": "Einschließlich Dienstkonten und API-Schlüssel",
            "mandatory": True,
            "forensic_critical": False,
            "order": 3,
        },
        {
            "item_id": "era_004",
            "phase": "eradication",
            "text": "Verify removal of persistence mechanisms",
            "text_de": "Entfernung von Persistenzmechanismen verifizieren",
            "help_text": "Check scheduled tasks, startup items, registry",
            "help_text_de": "Geplante Aufgaben, Startelemente, Registrierung prüfen",
            "mandatory": True,
            "forensic_critical": False,
            "order": 4,
            "depends_on": ["era_001"],
        },

        # ===== RECOVERY PHASE =====
        {
            "item_id": "rec_001",
            "phase": "recovery",
            "text": "Restore systems from clean backups",
            "text_de": "Systeme aus sauberen Backups wiederherstellen",
            "help_text": "Verify backup integrity before restoration",
            "help_text_de": "Backup-Integrität vor Wiederherstellung überprüfen",
            "mandatory": True,
            "forensic_critical": False,
            "order": 1,
        },
        {
            "item_id": "rec_002",
            "phase": "recovery",
            "text": "Gradually reconnect systems to network",
            "text_de": "Systeme schrittweise wieder mit dem Netzwerk verbinden",
            "help_text": "Phased approach with monitoring at each stage",
            "help_text_de": "Phasenweiser Ansatz mit Überwachung in jeder Phase",
            "mandatory": True,
            "forensic_critical": False,
            "order": 2,
            "depends_on": ["rec_001"],
        },
        {
            "item_id": "rec_003",
            "phase": "recovery",
            "text": "Verify system functionality and security",
            "text_de": "Systemfunktionalität und Sicherheit verifizieren",
            "help_text": "Confirm systems are operating normally and securely",
            "help_text_de": "Bestätigen, dass Systeme normal und sicher funktionieren",
            "mandatory": True,
            "forensic_critical": False,
            "order": 3,
            "depends_on": ["rec_002"],
        },
        {
            "item_id": "rec_004",
            "phase": "recovery",
            "text": "Implement additional security controls",
            "text_de": "Zusätzliche Sicherheitskontrollen implementieren",
            "help_text": "Address gaps identified during the incident",
            "help_text_de": "Während des Vorfalls identifizierte Lücken adressieren",
            "mandatory": False,
            "forensic_critical": False,
            "order": 4,
        },
        {
            "item_id": "rec_005",
            "phase": "recovery",
            "text": "Resume normal operations",
            "text_de": "Normalbetrieb wieder aufnehmen",
            "help_text": "Declare incident response complete for operations",
            "help_text_de": "Incident Response für den Betrieb als abgeschlossen erklären",
            "mandatory": True,
            "forensic_critical": False,
            "order": 5,
            "depends_on": ["rec_003"],
        },

        # ===== POST-INCIDENT PHASE =====
        {
            "item_id": "post_001",
            "phase": "post_incident",
            "text": "Conduct lessons learned meeting",
            "text_de": "Lessons-Learned-Meeting durchführen",
            "help_text": "Review what worked, what didn't, and improvements",
            "help_text_de": "Überprüfen Sie, was funktioniert hat, was nicht, und Verbesserungen",
            "mandatory": True,
            "forensic_critical": False,
            "order": 1,
        },
        {
            "item_id": "post_002",
            "phase": "post_incident",
            "text": "Create final incident report",
            "text_de": "Abschlussbericht des Vorfalls erstellen",
            "help_text": "Comprehensive documentation of the incident",
            "help_text_de": "Umfassende Dokumentation des Vorfalls",
            "mandatory": True,
            "forensic_critical": False,
            "order": 2,
        },
        {
            "item_id": "post_003",
            "phase": "post_incident",
            "text": "Update incident response procedures",
            "text_de": "Incident-Response-Verfahren aktualisieren",
            "help_text": "Incorporate lessons learned into playbooks",
            "help_text_de": "Erkenntnisse in Playbooks einarbeiten",
            "mandatory": False,
            "forensic_critical": False,
            "order": 3,
            "depends_on": ["post_001"],
        },
        {
            "item_id": "post_004",
            "phase": "post_incident",
            "text": "Archive evidence and documentation",
            "text_de": "Beweise und Dokumentation archivieren",
            "help_text": "Secure storage for legal and compliance purposes",
            "help_text_de": "Sichere Aufbewahrung für rechtliche und Compliance-Zwecke",
            "mandatory": True,
            "forensic_critical": True,
            "order": 4,
            "depends_on": ["post_002"],
        },
        {
            "item_id": "post_005",
            "phase": "post_incident",
            "text": "Complete regulatory notifications",
            "text_de": "Behördliche Meldungen abschließen",
            "help_text": "GDPR, BSI, industry-specific requirements",
            "help_text_de": "DSGVO, BSI, branchenspezifische Anforderungen",
            "mandatory": True,
            "forensic_critical": False,
            "order": 5,
        },
    ]

    for t in templates:
        template = ChecklistTemplate(
            id=str(uuid4()),
            item_id=t["item_id"],
            phase=t["phase"],
            text=t["text"],
            text_de=t["text_de"],
            help_text=t.get("help_text"),
            help_text_de=t.get("help_text_de"),
            warning=t.get("warning"),
            warning_de=t.get("warning_de"),
            mandatory=t.get("mandatory", False),
            forensic_critical=t.get("forensic_critical", False),
            order=t.get("order", 0),
            depends_on=t.get("depends_on", []),
            blocks=t.get("blocks", []),
        )
        db.add(template)

    await db.flush()
    print(f"Seeded {len(templates)} checklist templates")


async def seed_decision_trees(db: AsyncSession):
    """Seed decision trees and nodes."""

    # Check if already seeded
    result = await db.execute(select(DecisionTree).limit(1))
    if result.scalar_one_or_none():
        print("Decision trees already seeded")
        return

    # === CONTAINMENT STRATEGY TREE ===
    containment_tree = DecisionTree(
        id=str(uuid4()),
        tree_id="containment_strategy",
        phase="containment",
        name="Containment Strategy",
        name_de="Eindämmungsstrategie",
        description="Decide on the appropriate containment approach",
        description_de="Wählen Sie den geeigneten Eindämmungsansatz",
        entry_node_id="cs_001",
    )
    db.add(containment_tree)

    # Containment nodes
    cs_nodes = [
        DecisionNode(
            id=str(uuid4()),
            node_id="cs_001",
            tree_id="containment_strategy",
            phase="containment",
            title="Active Exfiltration Check",
            title_de="Prüfung auf aktive Exfiltration",
            question="Is there active data exfiltration occurring?",
            question_de="Findet eine aktive Datenexfiltration statt?",
            context="Check network monitoring for unusual outbound traffic",
            context_de="Überprüfen Sie die Netzwerküberwachung auf ungewöhnlichen ausgehenden Datenverkehr",
            is_entry_node=True,
            options=[
                {
                    "id": "cs_001_yes",
                    "label": "Yes, active exfiltration",
                    "label_de": "Ja, aktive Exfiltration",
                    "confidence": "high",
                    "next_node_id": "cs_002",
                    "requires_confirmation": False,
                },
                {
                    "id": "cs_001_no",
                    "label": "No active exfiltration",
                    "label_de": "Keine aktive Exfiltration",
                    "confidence": "high",
                    "next_node_id": "cs_003",
                },
                {
                    "id": "cs_001_unknown",
                    "label": "Unknown / Cannot determine",
                    "label_de": "Unbekannt / Nicht feststellbar",
                    "confidence": "low",
                    "next_node_id": "cs_002",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="cs_002",
            tree_id="containment_strategy",
            phase="containment",
            title="Immediate Disconnection",
            title_de="Sofortige Trennung",
            question="Should we immediately disconnect affected systems from the network?",
            question_de="Sollen betroffene Systeme sofort vom Netzwerk getrennt werden?",
            context="Immediate disconnection stops exfiltration but may alert the attacker and destroy volatile evidence",
            context_de="Sofortige Trennung stoppt Exfiltration, kann aber den Angreifer warnen und flüchtige Beweise zerstören",
            options=[
                {
                    "id": "cs_002_disconnect",
                    "label": "Yes, disconnect immediately",
                    "label_de": "Ja, sofort trennen",
                    "confidence": "high",
                    "next_node_id": "cs_004",
                    "requires_confirmation": True,
                    "modifies_evidence": True,
                },
                {
                    "id": "cs_002_monitor",
                    "label": "No, monitor and collect evidence first",
                    "label_de": "Nein, zuerst überwachen und Beweise sammeln",
                    "confidence": "medium",
                    "next_node_id": "cs_005",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="cs_003",
            tree_id="containment_strategy",
            phase="containment",
            title="Attacker Activity Check",
            title_de="Prüfung auf Angreiferaktivität",
            question="Is the attacker still active in the environment?",
            question_de="Ist der Angreifer noch in der Umgebung aktiv?",
            context="Look for active sessions, recent file modifications, or command execution",
            context_de="Suchen Sie nach aktiven Sitzungen, kürzlichen Dateiänderungen oder Befehlsausführung",
            options=[
                {
                    "id": "cs_003_active",
                    "label": "Yes, attacker is active",
                    "label_de": "Ja, Angreifer ist aktiv",
                    "confidence": "high",
                    "next_node_id": "cs_002",
                },
                {
                    "id": "cs_003_inactive",
                    "label": "No, appears dormant",
                    "label_de": "Nein, erscheint inaktiv",
                    "confidence": "medium",
                    "next_node_id": "cs_005",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="cs_004",
            tree_id="containment_strategy",
            phase="containment",
            title="Isolation Method Selection",
            title_de="Auswahl der Isolierungsmethode",
            question="Containment method for network isolation",
            question_de="Eindämmungsmethode für Netzwerkisolierung",
            context="Choose the most appropriate isolation technique",
            context_de="Wählen Sie die geeignetste Isolierungstechnik",
            options=[
                {
                    "id": "cs_004_vlan",
                    "label": "Move to isolated VLAN",
                    "label_de": "In isoliertes VLAN verschieben",
                    "confidence": "high",
                    "next_node_id": None,
                },
                {
                    "id": "cs_004_firewall",
                    "label": "Block at firewall level",
                    "label_de": "Auf Firewall-Ebene blockieren",
                    "confidence": "high",
                    "next_node_id": None,
                },
                {
                    "id": "cs_004_physical",
                    "label": "Physical network disconnection",
                    "label_de": "Physische Netzwerktrennung",
                    "confidence": "high",
                    "next_node_id": None,
                    "requires_confirmation": True,
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="cs_005",
            tree_id="containment_strategy",
            phase="containment",
            title="Monitoring-based Containment",
            title_de="Überwachungsbasierte Eindämmung",
            question="Implement monitoring-based containment?",
            question_de="Überwachungsbasierte Eindämmung implementieren?",
            context="Monitor attacker activity while preparing for full containment",
            context_de="Angreiferaktivität überwachen, während vollständige Eindämmung vorbereitet wird",
            options=[
                {
                    "id": "cs_005_yes",
                    "label": "Yes, implement enhanced monitoring",
                    "label_de": "Ja, verstärkte Überwachung implementieren",
                    "confidence": "medium",
                    "next_node_id": None,
                },
                {
                    "id": "cs_005_escalate",
                    "label": "Escalate to immediate containment",
                    "label_de": "Zu sofortiger Eindämmung eskalieren",
                    "confidence": "high",
                    "next_node_id": "cs_004",
                },
            ],
        ),
    ]

    for node in cs_nodes:
        db.add(node)

    # === DETECTION - INITIAL TRIAGE TREE ===
    triage_tree = DecisionTree(
        id=str(uuid4()),
        tree_id="initial_triage",
        phase="detection",
        name="Initial Triage",
        name_de="Erste Triage",
        description="Determine the nature and severity of the alert",
        description_de="Bestimmen Sie Art und Schwere der Warnung",
        entry_node_id="it_001",
    )
    db.add(triage_tree)

    # Initial triage nodes
    it_nodes = [
        DecisionNode(
            id=str(uuid4()),
            node_id="it_001",
            tree_id="initial_triage",
            phase="detection",
            title="Alert Source Verification",
            title_de="Überprüfung der Warnungsquelle",
            question="What is the source of this alert?",
            question_de="Was ist die Quelle dieser Warnung?",
            context="Identify where the alert originated to determine its reliability",
            context_de="Identifizieren Sie, woher die Warnung stammt, um ihre Zuverlässigkeit zu bestimmen",
            is_entry_node=True,
            options=[
                {
                    "id": "it_001_siem",
                    "label": "SIEM/EDR Detection",
                    "label_de": "SIEM/EDR-Erkennung",
                    "confidence": "high",
                    "next_node_id": "it_002",
                },
                {
                    "id": "it_001_user",
                    "label": "User Report",
                    "label_de": "Benutzermeldung",
                    "confidence": "medium",
                    "next_node_id": "it_002",
                },
                {
                    "id": "it_001_external",
                    "label": "External Notification (Vendor/Partner)",
                    "label_de": "Externe Benachrichtigung (Anbieter/Partner)",
                    "confidence": "medium",
                    "next_node_id": "it_003",
                },
                {
                    "id": "it_001_threat",
                    "label": "Threat Intelligence Feed",
                    "label_de": "Threat-Intelligence-Feed",
                    "confidence": "high",
                    "next_node_id": "it_002",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="it_002",
            tree_id="initial_triage",
            phase="detection",
            title="False Positive Assessment",
            title_de="Fehlalarm-Bewertung",
            question="Does this appear to be a false positive?",
            question_de="Scheint dies ein Fehlalarm zu sein?",
            context="Check for known false positive patterns, baseline behavior, and corroborating evidence",
            context_de="Prüfen Sie auf bekannte Fehlalarmmuster, normales Verhalten und bestätigende Beweise",
            options=[
                {
                    "id": "it_002_fp",
                    "label": "Yes, confirmed false positive",
                    "label_de": "Ja, bestätigter Fehlalarm",
                    "confidence": "high",
                    "next_node_id": None,
                    "recommendation": "Document and tune detection rules if needed",
                },
                {
                    "id": "it_002_tp",
                    "label": "No, appears to be genuine",
                    "label_de": "Nein, scheint echt zu sein",
                    "confidence": "high",
                    "next_node_id": "it_004",
                },
                {
                    "id": "it_002_uncertain",
                    "label": "Uncertain, needs more investigation",
                    "label_de": "Unsicher, weitere Untersuchung nötig",
                    "confidence": "low",
                    "next_node_id": "it_003",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="it_003",
            tree_id="initial_triage",
            phase="detection",
            title="Additional Evidence Gathering",
            title_de="Zusätzliche Beweiserhebung",
            question="What additional evidence should be gathered?",
            question_de="Welche zusätzlichen Beweise sollten gesammelt werden?",
            context="Collect more data to confirm or rule out the incident",
            context_de="Sammeln Sie mehr Daten, um den Vorfall zu bestätigen oder auszuschließen",
            options=[
                {
                    "id": "it_003_logs",
                    "label": "Review relevant system logs",
                    "label_de": "Relevante Systemprotokolle überprüfen",
                    "confidence": "medium",
                    "next_node_id": "it_002",
                },
                {
                    "id": "it_003_network",
                    "label": "Analyze network traffic",
                    "label_de": "Netzwerkverkehr analysieren",
                    "confidence": "medium",
                    "next_node_id": "it_002",
                },
                {
                    "id": "it_003_escalate",
                    "label": "Escalate to senior analyst",
                    "label_de": "An Senior-Analyst eskalieren",
                    "confidence": "medium",
                    "next_node_id": "it_002",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="it_004",
            tree_id="initial_triage",
            phase="detection",
            title="Incident Classification",
            title_de="Vorfallklassifizierung",
            question="What type of incident is this?",
            question_de="Um welche Art von Vorfall handelt es sich?",
            context="Classify the incident to determine the appropriate response playbook",
            context_de="Klassifizieren Sie den Vorfall, um das geeignete Reaktions-Playbook zu bestimmen",
            options=[
                {
                    "id": "it_004_malware",
                    "label": "Malware/Ransomware",
                    "label_de": "Malware/Ransomware",
                    "confidence": "high",
                    "next_node_id": "it_005",
                },
                {
                    "id": "it_004_phishing",
                    "label": "Phishing/Social Engineering",
                    "label_de": "Phishing/Social Engineering",
                    "confidence": "high",
                    "next_node_id": "it_005",
                },
                {
                    "id": "it_004_unauthorized",
                    "label": "Unauthorized Access",
                    "label_de": "Unbefugter Zugriff",
                    "confidence": "high",
                    "next_node_id": "it_005",
                },
                {
                    "id": "it_004_data",
                    "label": "Data Breach/Exfiltration",
                    "label_de": "Datenschutzverletzung/Exfiltration",
                    "confidence": "high",
                    "next_node_id": "it_005",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="it_005",
            tree_id="initial_triage",
            phase="detection",
            title="Severity Assessment",
            title_de="Schweregradbewertung",
            question="What is the initial severity assessment?",
            question_de="Wie lautet die erste Schweregradbewertung?",
            context="Based on affected systems, data sensitivity, and potential impact",
            context_de="Basierend auf betroffenen Systemen, Datensensitivität und potenziellen Auswirkungen",
            options=[
                {
                    "id": "it_005_critical",
                    "label": "Critical - Immediate response required",
                    "label_de": "Kritisch - Sofortige Reaktion erforderlich",
                    "confidence": "high",
                    "next_node_id": None,
                    "next_phase": "analysis",
                },
                {
                    "id": "it_005_high",
                    "label": "High - Urgent investigation needed",
                    "label_de": "Hoch - Dringende Untersuchung erforderlich",
                    "confidence": "high",
                    "next_node_id": None,
                    "next_phase": "analysis",
                },
                {
                    "id": "it_005_medium",
                    "label": "Medium - Investigation within 24 hours",
                    "label_de": "Mittel - Untersuchung innerhalb von 24 Stunden",
                    "confidence": "medium",
                    "next_node_id": None,
                    "next_phase": "analysis",
                },
                {
                    "id": "it_005_low",
                    "label": "Low - Monitor and document",
                    "label_de": "Niedrig - Überwachen und dokumentieren",
                    "confidence": "medium",
                    "next_node_id": None,
                },
            ],
        ),
    ]

    for node in it_nodes:
        db.add(node)

    # === RANSOMWARE RESPONSE TREE ===
    ransomware_tree = DecisionTree(
        id=str(uuid4()),
        tree_id="ransomware_response",
        phase="analysis",
        name="Ransomware Response",
        name_de="Ransomware-Reaktion",
        description="Decision tree for ransomware incident response",
        description_de="Entscheidungsbaum für die Reaktion auf Ransomware-Vorfälle",
        entry_node_id="rr_001",
    )
    db.add(ransomware_tree)

    rr_nodes = [
        DecisionNode(
            id=str(uuid4()),
            node_id="rr_001",
            tree_id="ransomware_response",
            phase="analysis",
            title="Active Encryption Check",
            title_de="Prüfung auf aktive Verschlüsselung",
            question="Is the ransomware still actively encrypting files?",
            question_de="Verschlüsselt die Ransomware noch aktiv Dateien?",
            context="Check for high disk I/O, new encrypted file extensions appearing",
            context_de="Prüfen Sie auf hohe Festplatten-I/O, neue verschlüsselte Dateierweiterungen",
            is_entry_node=True,
            options=[
                {
                    "id": "rr_001_active",
                    "label": "Yes, encryption in progress",
                    "label_de": "Ja, Verschlüsselung läuft",
                    "confidence": "high",
                    "next_node_id": "rr_002",
                },
                {
                    "id": "rr_001_stopped",
                    "label": "No, encryption has stopped",
                    "label_de": "Nein, Verschlüsselung gestoppt",
                    "confidence": "high",
                    "next_node_id": "rr_003",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="rr_002",
            tree_id="ransomware_response",
            phase="analysis",
            title="Immediate Isolation Decision",
            title_de="Entscheidung zur sofortigen Isolation",
            question="Should we immediately isolate affected systems?",
            question_de="Sollen betroffene Systeme sofort isoliert werden?",
            context="Isolation will stop encryption spread but the process should be killed first if possible",
            context_de="Isolation stoppt die Ausbreitung, aber der Prozess sollte wenn möglich zuerst beendet werden",
            options=[
                {
                    "id": "rr_002_isolate",
                    "label": "Yes, isolate immediately",
                    "label_de": "Ja, sofort isolieren",
                    "confidence": "high",
                    "next_node_id": "rr_003",
                    "requires_confirmation": True,
                },
                {
                    "id": "rr_002_kill",
                    "label": "Kill process first, then isolate",
                    "label_de": "Zuerst Prozess beenden, dann isolieren",
                    "confidence": "high",
                    "next_node_id": "rr_003",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="rr_003",
            tree_id="ransomware_response",
            phase="analysis",
            title="Backup Availability Check",
            title_de="Prüfung der Backup-Verfügbarkeit",
            question="Do we have viable backups for affected data?",
            question_de="Haben wir funktionsfähige Backups für betroffene Daten?",
            context="Check backup systems, verify backups are not encrypted",
            context_de="Backup-Systeme prüfen, verifizieren dass Backups nicht verschlüsselt sind",
            options=[
                {
                    "id": "rr_003_yes",
                    "label": "Yes, backups are available and clean",
                    "label_de": "Ja, Backups sind verfügbar und sauber",
                    "confidence": "high",
                    "next_node_id": "rr_004",
                },
                {
                    "id": "rr_003_partial",
                    "label": "Partial backups available",
                    "label_de": "Teilweise Backups verfügbar",
                    "confidence": "medium",
                    "next_node_id": "rr_005",
                },
                {
                    "id": "rr_003_no",
                    "label": "No viable backups",
                    "label_de": "Keine funktionsfähigen Backups",
                    "confidence": "low",
                    "next_node_id": "rr_005",
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="rr_004",
            tree_id="ransomware_response",
            phase="analysis",
            title="Restoration Decision",
            title_de="Wiederherstellungsentscheidung",
            question="Proceed with restoration from backups?",
            question_de="Mit Wiederherstellung aus Backups fortfahren?",
            context="Ensure malware is fully eradicated before restoration",
            context_de="Stellen Sie sicher, dass Malware vor der Wiederherstellung vollständig entfernt ist",
            options=[
                {
                    "id": "rr_004_restore",
                    "label": "Yes, begin restoration process",
                    "label_de": "Ja, Wiederherstellungsprozess beginnen",
                    "confidence": "high",
                    "next_node_id": None,
                    "next_phase": "recovery",
                },
                {
                    "id": "rr_004_wait",
                    "label": "Wait for full eradication confirmation",
                    "label_de": "Auf vollständige Löschungsbestätigung warten",
                    "confidence": "medium",
                    "next_node_id": None,
                },
            ],
        ),
        DecisionNode(
            id=str(uuid4()),
            node_id="rr_005",
            tree_id="ransomware_response",
            phase="analysis",
            title="Variant Identification",
            title_de="Variantenidentifikation",
            question="Should we attempt to identify the ransomware variant?",
            question_de="Sollen wir versuchen, die Ransomware-Variante zu identifizieren?",
            context="Known variants may have free decryption tools available",
            context_de="Für bekannte Varianten können kostenlose Entschlüsselungstools verfügbar sein",
            options=[
                {
                    "id": "rr_005_identify",
                    "label": "Yes, identify variant (nomoreransom.org)",
                    "label_de": "Ja, Variante identifizieren (nomoreransom.org)",
                    "confidence": "medium",
                    "next_node_id": None,
                },
                {
                    "id": "rr_005_skip",
                    "label": "Skip, proceed with eradication",
                    "label_de": "Überspringen, mit Löschung fortfahren",
                    "confidence": "high",
                    "next_node_id": None,
                    "next_phase": "eradication",
                },
            ],
        ),
    ]

    for node in rr_nodes:
        db.add(node)

    await db.flush()
    print("Seeded 3 decision trees with nodes")


async def run_seed(db: AsyncSession):
    """Run all seed functions."""
    print("Starting database seed...")
    await seed_checklist_templates(db)
    await seed_decision_trees(db)
    await db.commit()
    print("Database seed completed!")
