"""add_sso_tables_and_user_sso_fields

Revision ID: 3fdaec0013d5
Revises: 
Create Date: 2026-01-31 23:27:07.234868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdaec0013d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=500), nullable=False),
    sa.Column('authorization_url', sa.String(length=500), nullable=False),
    sa.Column('token_url', sa.String(length=500), nullable=False),
    sa.Column('userinfo_url', sa.String(length=500), nullable=False),
    sa.Column('scopes', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_role', sa.String(length=50), nullable=False),
    sa.Column('allowed_domains', sa.Text(), nullable=True),
    sa.Column('auto_create_users', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('button_text', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sso_providers_slug'), 'sso_providers', ['slug'], unique=True)
    op.create_table('sso_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('provider_slug', sa.String(length=50), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sso_states_state'), 'sso_states', ['state'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('EVIDENCE', 'SCREENSHOT', 'LOG_FILE', 'DOCUMENT', 'REPORT', 'PCAP', 'MEMORY_DUMP', 'MALWARE_SAMPLE', 'OTHER', name='attachmentcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Enum('INCIDENT', 'VULNERABILITY', 'CASE', 'ALERT', 'RISK', 'VENDOR', 'ASSET', 'EVIDENCE', 'REPORT', 'GENERAL', name='attachmententitytype'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('last_downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_category', 'attachments', ['category'], unique=False)
    op.create_index('ix_attachments_entity', 'attachments', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_attachments_file_hash', 'attachments', ['file_hash'], unique=False)
    op.create_index('ix_attachments_uploaded_by', 'attachments', ['uploaded_by'], unique=False)
    op.add_column('activity_logs', sa.Column('action_category', sa.String(length=50), nullable=True))
    op.add_column('activity_logs', sa.Column('resource_name', sa.String(), nullable=True))
    op.add_column('activity_logs', sa.Column('changes_summary', sa.Text(), nullable=True))
    op.add_column('activity_logs', sa.Column('request_id', sa.String(), nullable=True))
    op.add_column('activity_logs', sa.Column('severity', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_type'), 'activity_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('sso_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sso_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sso_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sso_linked_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_sso_id'), 'users', ['sso_id'], unique=False)
    op.add_column('vulnerability_scans', sa.Column('celery_task_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_vulnerability_scans_celery_task_id'), 'vulnerability_scans', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_scans_celery_task_id'), table_name='vulnerability_scans')
    op.drop_column('vulnerability_scans', 'celery_task_id')
    op.drop_index(op.f('ix_users_sso_id'), table_name='users')
    op.drop_column('users', 'sso_linked_at')
    op.drop_column('users', 'sso_email')
    op.drop_column('users', 'sso_id')
    op.drop_column('users', 'sso_provider')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_resource_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_column('activity_logs', 'severity')
    op.drop_column('activity_logs', 'request_id')
    op.drop_column('activity_logs', 'changes_summary')
    op.drop_column('activity_logs', 'resource_name')
    op.drop_column('activity_logs', 'action_category')
    op.drop_index('ix_attachments_uploaded_by', table_name='attachments')
    op.drop_index('ix_attachments_file_hash', table_name='attachments')
    op.drop_index('ix_attachments_entity', table_name='attachments')
    op.drop_index('ix_attachments_category', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_sso_states_state'), table_name='sso_states')
    op.drop_table('sso_states')
    op.drop_index(op.f('ix_sso_providers_slug'), table_name='sso_providers')
    op.drop_table('sso_providers')
    # ### end Alembic commands ###
